#!/usr/bin/env python3
"""Generate font_6x8_subpixel.h from font_6x8.h.

The source font is 6 pixels wide. On the LilyGO ST7735 panel each
panel pixel exposes 3 horizontal subpixels (BGR — MADCTL bit 0x08
always set per lib/lcd_st7735/st7735.cpp), so 6 source pixels map
1:1 onto 6 subpixels = 2 panel pixels. There is no upsampling: a
source bit drives a subpixel directly; the [1,2,1]/4 filter just
softens the color fringes between adjacent on/off transitions.

For each of 256 glyphs, each of 8 rows:
1. Read 6 source bits from the high 6 bits of the row byte.
2. Apply a 3-tap [1, 2, 1] / 4 filter (edge-clamp at indices 0 and 5).
3. Pack into 2 panel pixels per row. Each panel pixel takes 3
   consecutive subpixels; BGR ordering means subpixel 0 of each
   panel pixel drives B, 1 drives G, 2 drives R.

Output: static const uint16_t font_subpixel[256][8][2].

Use --check to verify the committed file matches the generator output
(returns exit 1 on mismatch). Used by Task 8's host test.
"""

import argparse, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC  = ROOT / "firmware/components/display/include/font_6x8.h"
DST  = ROOT / "firmware/components/display/include/font_6x8_subpixel.h"


def parse_font_6x8(path):
    """Return list of 256 lists of 8 ints from font_6x8.h."""
    text = path.read_text()
    rx = re.compile(r"\[0x([0-9a-fA-F]{2})\]\s*=\s*\{([^}]*)\}")
    out = [[0]*8 for _ in range(256)]
    for m in rx.finditer(text):
        idx = int(m.group(1), 16)
        bytes_ = [int(b.strip(), 0) for b in m.group(2).split(",") if b.strip()]
        out[idx] = (bytes_[:8] + [0]*8)[:8]
    return out


def render_glyph(rows):
    """Return [8][2] of uint16 RGB565 with BGR-mapped subpixel intensities."""
    out = [[0, 0] for _ in range(8)]
    for y, row_byte in enumerate(rows):
        # 6 source bits drive 6 subpixels directly (no upsampling).
        s = [(row_byte >> (7 - x)) & 1 for x in range(6)]
        # 3-tap [1,2,1]/4 filter, edge-clamp at row endpoints.
        f = [0.0] * 6
        for k in range(6):
            left  = s[k - 1] if k > 0 else s[0]
            ctr   = s[k]
            right = s[k + 1] if k < 5 else s[5]
            f[k]  = (left + 2 * ctr + right) / 4.0
        # Pack 2 panel pixels per row. Each = 3 subpixels (B, G, R for BGR).
        for cell in range(2):
            sub_b = f[cell * 3 + 0]
            sub_g = f[cell * 3 + 1]
            sub_r = f[cell * 3 + 2]
            r5 = max(0, min(31, int(round(sub_r * 31))))
            g6 = max(0, min(63, int(round(sub_g * 63))))
            b5 = max(0, min(31, int(round(sub_b * 31))))
            out[y][cell] = (r5 << 11) | (g6 << 5) | b5
    return out


def render_all(font):
    return [render_glyph(font[code]) for code in range(256)]


def emit_text(table):
    """Render the .h file to a string. Used by both write and --check."""
    lines = [
        "/* Auto-generated by tools/build_subpixel_font.py.",
        " * Do not edit by hand. Regenerate after editing font_6x8.h:",
        " *     python tools/build_subpixel_font.py",
        " *",
        " * Layout: font_subpixel[code][row][cell], where each row of a",
        " * glyph occupies 2 panel pixels (6 subpixels) horizontally.",
        " * RGB565 packed for a BGR-ordered ST7735 panel — subpixel 0 of",
        " * each cell drives blue, 1 green, 2 red.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "static const uint16_t font_subpixel[256][8][2] = {",
    ]
    for code in range(256):
        glyph = table[code]
        lines.append(f"    [0x{code:02x}] = {{")
        for row in glyph:
            cells = ", ".join(f"0x{c:04x}" for c in row)
            lines.append(f"        {{ {cells} }},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Verify committed file matches generator output; exit 1 if not.")
    args = ap.parse_args()

    font = parse_font_6x8(SRC)
    table = render_all(font)
    text = emit_text(table)

    if args.check:
        committed = DST.read_text() if DST.exists() else ""
        # Normalize line endings before comparing — Windows git may have
        # converted to CRLF.
        if text.replace("\r\n", "\n") != committed.replace("\r\n", "\n"):
            sys.stderr.write(
                "font_6x8_subpixel.h is out of date — re-run:\n"
                "    python tools/build_subpixel_font.py\n"
            )
            return 1
        print("font_6x8_subpixel.h matches generator output")
        return 0

    DST.write_text(text)
    print(f"wrote {DST} ({len(font)} glyphs, {len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
